version: "2"
services:
  zookeeper-1:
    image: zookeeper
    restart: always
    ports:
      - 2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper-1:2888:3888
#      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888

#  zookeeper-2:
#    image: zookeeper
#    restart: always
#    ports:
#      - 2181
#    environment:
#      ZOO_MY_ID: 2
#      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888
#
#  zookeeper-3:
#    image: zookeeper
#    restart: always
#    ports:
#      - 2181
#    environment:
#      ZOO_MY_ID: 3
#      ZOO_SERVERS: server.1=zookeeper-1:2888:3888 server.2=zookeeper-2:2888:3888 server.3=zookeeper-3:2888:3888

  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.7.1-java8
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_resourcemanager_recovery_enabled=true
      - YARN_CONF_yarn_resourcemanager_store_class=org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
      - YARN_CONF_yarn_resourcemanager_fs_state___store_uri=/rmstate
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
      - YARN_CONF_yarn_log_server_url=http://historyserver:8188/applicationhistory/logs/
      - YARN_CONF_yarn_timeline___service_enabled=true
      - YARN_CONF_yarn_timeline___service_generic___application___history_enabled=true
      - YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled=true
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - YARN_CONF_yarn_timeline___service_hostname=historyserver
      - YARN_CONF_yarn_resourcemanager_address=resourcemanager:8032
      - YARN_CONF_yarn_resourcemanager_scheduler_address=resourcemanager:8030
      - YARN_CONF_yarn_resourcemanager_resource__tracker_address=resourcemanager:8031
      - CORE_CONF_hadoop_proxyuser_hbase_hosts=*
      - CORE_CONF_hadoop_proxyuser_hbase_groups=*
      - HDFS_CONF_dfs_permissions_enabled=false

  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
    container_name: datanode
    depends_on: 
      - namenode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_resourcemanager_recovery_enabled=true
      - YARN_CONF_yarn_resourcemanager_store_class=org.apache.hadoop.yarn.server.resourcemanager.recovery.FileSystemRMStateStore
      - YARN_CONF_yarn_resourcemanager_fs_state___store_uri=/rmstate
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
      - YARN_CONF_yarn_log_server_url=http://historyserver:8188/applicationhistory/logs/
      - YARN_CONF_yarn_timeline___service_enabled=true
      - YARN_CONF_yarn_timeline___service_generic___application___history_enabled=true
      - YARN_CONF_yarn_resourcemanager_system___metrics___publisher_enabled=true
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - YARN_CONF_yarn_timeline___service_hostname=historyserver
      - YARN_CONF_yarn_resourcemanager_address=resourcemanager:8032
      - YARN_CONF_yarn_resourcemanager_scheduler_address=resourcemanager:8030
      - YARN_CONF_yarn_resourcemanager_resource__tracker_address=resourcemanager:8031
      - CORE_CONF_hadoop_proxyuser_hbase_hosts=*
      - CORE_CONF_hadoop_proxyuser_hbase_groups=*
      - HDFS_CONF_dfs_permissions_enabled=false

  hmaster:
    container_name: hmaster
    #image: smizy/hbase:1.2.4-alpine
    build: .
    expose: [16000]
    ports:  [16010]
    depends_on: ["zookeeper-1"]
    environment:
      - SERVICE_16000_NAME=hmaster
      - SERVICE_16010_IGNORE=true
      - HADOOP_VERSION=2.7.1
      - HADOOP_NAMENODE1_HOSTNAME=namenode
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HBASE_HMASTER1_HOSTNAME=hmaster
      - HBASE_ROOT_DIR=hdfs://namenode:8020/hbase
      - HBASE_REGIONSERVER1_HOSTNAME=regionserver
    #  - HBASE_ZOOKEEPER_QUORUM=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181 
      - HBASE_ZOOKEEPER_QUORUM=zookeeper-1:2181
    volumes_from:
      - namenode
    command: hmaster-1

  regionserver:
    container_name: regionserver
    #image: smizy/hbase:1.2.4-alpine
    build: .
    expose: [16020, 16030]
    depends_on: ["zookeeper-1"]
    environment:
      - SERVICE_16020_NAME=regionserver
      - SERVICE_16030_IGNORE=true
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HADOOP_VERSION=2.7.1
      - HADOOP_NAMENODE1_HOSTNAME=namenode
      - HBASE_HMASTER1_HOSTNAME=hmaster
      - HBASE_ROOT_DIR=hdfs://namenode:8020/hbase
      - HBASE_REGIONSERVER1_HOSTNAME=regionserver
     # - HBASE_ZOOKEEPER_QUORUM=zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181 
      - HBASE_ZOOKEEPER_QUORUM=zookeeper-1:2181
    command: regionserver

volumes:
    hadoop_namenode:
    hadoop_datanode:
